services:
  basuracero-app:
    build: .
    network_mode: "host"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - TZ=Europe/Madrid
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5050', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped