services:
  basuracero-app:
    build:
      context: .
      args:
        - PORT=${PORT:-5050}
    network_mode: "host"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - TZ=Europe/Madrid
      - PORT=${PORT:-5050}
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:' + process.env.PORT, (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped